# aa
```{r}
#| context: setup
library(gt)
library(dplyr)
library(ggplot2)
library(purrr)
library(ggiraph)
library(htmltools)
library(reactable)
```

```{r}
#| include: false
source("./data/CVM/R/07_Indicadores.R")

```

## {.sidebar}

```{r}
HTML('
  <div>
    <div style="font-weight:600">Período</div>
    <div id="period_radio_div">',
      paste0(
        lapply(unique(struct_trimestre$PERIODO), function(x) {
          checked <- ifelse(x == unique(struct_trimestre$PERIODO)[1], "checked", "")
          paste0(
            '<input type="radio" name="period_radio" value="', x, '" ', checked, '>',
            '<label>', x, '</label>',
            '<br>'
          )
        }), collapse = ""
      ),
    '</div>
  </div>
  <script>
    console.log("Script loaded.");
    var period_radios = document.getElementsByName("period_radio");
    console.log("Period radios:", period_radios);
    period_radios.forEach(function(radio) {
      radio.addEventListener("change", function() {
        console.log("Change event triggered");
        updateTable();
      });
    });

    function updateTable() {
      console.log("Updating table...");
      var selectedPeriod = document.querySelector(\'input[name="period_radio"]:checked\').value;
      console.log("Selected period:", selectedPeriod);
      var rows = document.querySelectorAll("#indicadores tbody tr");
      console.log("Number of rows:", rows.length);
      rows.forEach(function(row) {
        var rowPeriods = row.getAttribute("data-period").split(",");
        console.log("Row periods:", rowPeriods);
        if (rowPeriods.includes(selectedPeriod)) {
          row.style.display = "";
        } else {
          row.style.display = "none";
        }
      });
    }
    updateTable(); // Adicionando esta linha para selecionar o primeiro período inicialmente
  </script>'
)


```

## Main Body

### First row {height="70%"}

#### Row {.tabset}



```{r}
#| title: INDICADORES DE LIQUIDEZ

# Formatando os números com duas casas decimais e separados por vírgula
# ind_liquidez$liq_geral <- formatC(ind_liquidez$liq_geral, format = "f", digits = 2, decimal.mark = ",", big.mark = ".", width = NULL)
# ind_liquidez$liq_corrente <- formatC(ind_liquidez$liq_corrente, format = "f", digits = 2, decimal.mark = ",", big.mark = ".", width = NULL)
# ind_liquidez$liq_seca <- formatC(ind_liquidez$liq_seca, format = "f", digits = 2, decimal.mark = ",", big.mark = ".", width = NULL)
# ind_liquidez$liq_imediata <- formatC(ind_liquidez$liq_imediata, format = "f", digits = 2, decimal.mark = ",", big.mark = ".", width = NULL)

DT::datatable(
  indicadores, 
  extensions = 'FixedHeader',
  rownames = F,
  # colnames = c('Empresa' = 'EMPRESA',
  #              'Liquidez Geral' = "liq_geral", 
  #              'Liquidez Corrente' = "liq_corrente",
  #              'Liquidez Seca' = "liq_seca",
  #              'Liquidez Imediata' = "liq_imediata"),
  options = list(
    pageLength = 10,
    initComplete = JS(
      "function(settings, json) {",
      "$(this.api().table().header()).css({
      'background-color': '#B52730', 
      'color': '#fff'});","}"),
    width = '100%',
    align = 'center'
    ),
  elementId = "indicadores"
)


```

