# Indicadores

```{r}
#| include: false
source("./data/CVM/R/07_Indicadores.R")

#| include: false
selected_quarter <- c("2023")  # Defina o período


```

## {.sidebar}

```{ojs}
//| panel: input

viewof selected_quarter = Inputs.select(
  ["2023", "2022", "2021", "2020"], 
  { value: "2023", 
    label: "Período:"
  }
)


```

## Main Body

### First row {height="70%"}

#### Row {.tabset}

```{r}
#| title: INDICADORES DE LIQUIDEZ

library(DT)

# Filtre os indicadores com base no trimestre selecionado
filtered_indicators <- indicadores[indicadores$PERIODO.x == selected_quarter, ]

# Criando a tabela indicadores filtrados
datatable(
  filtered_indicators %>%
    select(Empresa = EMPRESA.x, 
           Período = PERIODO.x, 
           `Liquidez Geral` = liq_geral, 
           `Liquidez Corrente` = liq_corrente, 
           `Liquidez Seca` = liq_seca, 
           `Liquidez Imediata` = liq_imediata), 
  extensions = 'FixedHeader',
  rownames = FALSE,
  options = list(
    pageLength = 10,
    width = '100%',
    align = 'center'
  )
)



```

### Second row {height="70%"}

#### Row {.tabset}

```{r}
#| title: INDICADORES DE LUCRATIVIDADE

library(DT)

# Filtre os indicadores com base no trimestre selecionado
filtered_indicators <- indicadores[indicadores$PERIODO.x == selected_quarter, ]

# Criando a tabela indicadores filtrados
datatable(
  filtered_indicators %>%
    select(Empresa = EMPRESA.x, 
           Período = PERIODO.x, 
           `Margem Bruta` = margem_bruta, 
           `Margem EBIT` = margem_ebit, 
           `Margem Líquida` = margem_liquida), 
  extensions = 'FixedHeader',
  rownames = FALSE,
  options = list(
    pageLength = 10,
    width = '100%',
    align = 'center'
  )
)



```